# Generated by Django 3.2.9 on 2021-11-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=512)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('description', models.TextField()),
                ('source', models.URLField(max_length=512, null=True)),
                ('downvoters', models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL)),
                ('poaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='museum.Tag')),
                ('upvoters', models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
