# Generated by Django 3.2.9 on 2021-11-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_meme_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meme',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
