# Generated by Django 3.2.9 on 2021-11-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
