# Generated by Django 3.2.9 on 2021-11-28 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
