# Generated by Django 3.2.9 on 2021-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='meme_lord',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
